name: niniland
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player: ^2.0.13+8
  blur: ^1.0.1
  cupertino_icons: ^1.0.2
  fdottedline: ^1.0.1
  firebase_core: ^0.5.2
  firebase_messaging: ^7.0.3
  flare_flutter: ^2.0.6
  flutter_automation: ^1.4.0
  flutter_screenutil: ^4.0.3+1
  flutter_svg: ^0.19.3
  http: ^0.12.2
  path_provider: ^1.6.8
  pimp_my_button: ^1.0.0
  provider: ^4.3.3
  slide_to_act: ^0.1.3+1
  snappable: ^1.0.1
  spring: ^1.0.4
  universal_io: ^1.0.2
  url_launcher: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/images/
    - assets/audios/
    - assets/audios/sounds/
    - assets/audios/lullabies/

  fonts:
    - family: aseman
      fonts:
        - asset: assets/fonts/aseman.ttf
    - family: IRANSans
      fonts:
        - asset: assets/fonts/IRANSansBold.ttf
          weight: 500
        - asset: assets/fonts/IRANSansMedium.ttf
          weight: 400
        - asset: assets/fonts/IRANSans.ttf
          weight: 300
        - asset: assets/fonts/IRANSansLight.ttf
          weight: 200
        - asset: assets/fonts/IRANSansUltraLight.ttf
          weight: 100
